# Generated by Django 4.2.5 on 2023-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postactivity",
            name="occurred_at",
            field=models.DateField(),
        ),
    ]
